import type { Metadata } from "next";
import "./globals.css";
import { getCurrentUser } from "./actions/auth-actions";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Auth-NextJS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser()


  return (
    <html lang="es">
      <body>
        <Header user={user} />
        <main>{children}</main>
      </body>
    </html>
  )
}
